pipeline{

	agent any

	environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub-cred-paulo')
    commit = sh(returnStdout: true, script: 'git log --format="%H" -n 1')
    imageTag = sh(returnStdout: true, script: "echo ${env.BUILD_NUMBER}.${env.commit}")
	}

	stages {
		stage('Build') {
			steps {
				sh "docker build -t paulokinjo/python-superlist:${env.imageTag} ."
			}
		}

		stage('Login') {

			steps {
				sh "echo ${DOCKERHUB_CREDENTIALS_PSW} | docker login -u ${DOCKERHUB_CREDENTIALS_USR} --password-stdin"
			}
		}

		stage('Push') {
			steps {
				sh "docker push paulokinjo/python-superlist:${env.imageTag}"
			}
		}
	}

	post {
		always {
			sh 'docker logout'
		}
	}

}