pipeline {

	agent any

	environment {
		DOCKERHUB_CREDENTIALS = 'dockerhub-cred-paulo'
    imageName             = "paulokinjo/python-superlists"
    commit                = sh(returnStdout: true, script: 'git log --format="%H" -n 1')
    imageTag              = sh(returnStdout: true, script: "echo ${env.BUILD_NUMBER}.${env.commit}")    
    dockerImage           = ''
	}

	stages {
    stage ('temp') {
      steps {
        echo "${env.DOCKERHUB_CREDENTIALS}"
        echo "${env.imageName}"
        echo "${env.commit}"
        echo "${env.imageTag}"
        echo "${env.dockerImage}_"
      }
    }

		stage('Build') {
			steps {
        script {
          dockerImage = docker.build imagename
        }
			}
		}

		stage('Deploy') {      
			steps {
        script {
          docker.withRegistry( '', DOCKERHUB_CREDENTIALS ) {
            dockerImage.push("$BUILD_NUMBER")
            dockerImage.push(imageTag)
          }
        }
			}
		}
	}

	post {
		always {
			sh 'docker logout'
      // sh "docker rmi $imagename:$BUILD_NUMBER"
      // sh "docker rmi $imagename:$imageTag"
		}
	}

}